//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : AUMS
	/// Data Source    : localhost
	/// Server Version : 15.00.4102
	/// </summary>
	public partial class AUMSDB : LinqToDB.Data.DataConnection
	{
		public ITable<IpInfo>   IpInfos   { get { return this.GetTable<IpInfo>(); } }
		public ITable<UserInfo> UserInfos { get { return this.GetTable<UserInfo>(); } }

		public AUMSDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(LinqToDbConnectionOptions<AUMSDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="IpInfos")]
	public partial class IpInfo
	{
		[PrimaryKey, Identity] public int    IpInfoId     { get; set; } // int
		[Column,     Nullable] public string IpAddress    { get; set; } // varchar(16)
		[Column,     Nullable] public short? GrantSend    { get; set; } // smallint
		[Column,     Nullable] public int?   UserInfoId   { get; set; } // int
		[Column,     Nullable] public bool?  PermissionYN { get; set; } // bit
		[Column,     Nullable] public bool?  UseYN        { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK_IpInfos_UserInfoId_UserInfos_UserInfoId
		/// </summary>
		[Association(ThisKey="UserInfoId", OtherKey="UserInfoId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_IpInfos_UserInfoId_UserInfos_UserInfoId", BackReferenceName="IpInfosUserInfoIdUserInfoIds")]
		public UserInfo UserInfo { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="UserInfos")]
	public partial class UserInfo
	{
		[PrimaryKey, Identity] public int    UserInfoId { get; set; } // int
		[Column,     Nullable] public string EmpNo      { get; set; } // char(5)
		[Column,     Nullable] public string CmpCode    { get; set; } // char(2)

		#region Associations

		/// <summary>
		/// FK_IpInfos_UserInfoId_UserInfos_UserInfoId_BackReference
		/// </summary>
		[Association(ThisKey="UserInfoId", OtherKey="UserInfoId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<IpInfo> IpInfosUserInfoIdUserInfoIds { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static IpInfo Find(this ITable<IpInfo> table, int IpInfoId)
		{
			return table.FirstOrDefault(t =>
				t.IpInfoId == IpInfoId);
		}

		public static UserInfo Find(this ITable<UserInfo> table, int UserInfoId)
		{
			return table.FirstOrDefault(t =>
				t.UserInfoId == UserInfoId);
		}
	}
}

#pragma warning restore 1591
