//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : AUMS
	/// Data Source    : localhost
	/// Server Version : 15.00.4102
	/// </summary>
	public partial class AUMSDB : LinqToDB.Data.DataConnection
	{
		public ITable<IpInfo> IpInfo { get { return this.GetTable<IpInfo>(); } }

		public AUMSDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AUMSDB(LinqToDbConnectionOptions<AUMSDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="IpInfo")]
	public partial class IpInfo
	{
		[PrimaryKey, Identity] public int    IpInfoId  { get; set; } // int
		[Column,     NotNull ] public string IpAddress { get; set; } // varchar(16)
		[Column,     NotNull ] public short  GrantSend { get; set; } // smallint
	}

	public static partial class TableExtensions
	{
		public static IpInfo Find(this ITable<IpInfo> table, int IpInfoId)
		{
			return table.FirstOrDefault(t =>
				t.IpInfoId == IpInfoId);
		}
	}
}

#pragma warning restore 1591
