Create Login MT with password = 'q1w2e3r4t5Y^U&I*O(P)';
Create DATABASE AUMS;

GO

Use AUMS;  
CREATE USER MT FOR LOGIN MT;
GRANT CREATE TABLE TO MT;
GRANT ALTER, SELECT, INSERT ON SCHEMA::dbo TO MT;

GO